import Container from '@/components/ui/container';
import Header from '@/components/ui/header';
import { ReactNode } from 'react';

export const metadata = {
  title: 'Dashboard | To Do App',
  description: 'Generated by create next app',
};

type DashboardLayoutProps = {
  children: ReactNode;
};

export default function DashboardLayout({ children }: DashboardLayoutProps) {
  return (
    <>
      <Container>
        <Header />
        <main className='min-h-screen flex flex-col w-full items-center justify-center mx-20'>
          {children}
        </main>
      </Container>
    </>
  );
}
